In [1]:
%pip install google-generativeai pandas tabulate

Collecting google-generativeai
  Using cached google_generativeai-0.8.6-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: pandas in d:\anaconda\lib\site-packages (2.2.3)
Requirement already satisfied: tabulate in d:\anaconda\lib\site-packages (0.9.0)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in d:\anaconda\lib\site-packages (from google-generativeai) (0.6.15)
Requirement already satisfied: google-api-core in d:\anaconda\lib\site-packages (from google-generativeai) (2.29.0)
Requirement already satisfied: google-api-python-client in d:\anaconda\lib\site-packages (from google-generativeai) (2.188.0)
Requirement already satisfied: google-auth>=2.15.0 in d:\anaconda\lib\site-packages (from google-generativeai) (2.49.0.dev0)
Requirement already satisfied: protobuf in d:\anaconda\lib\site-packages (from google-generativeai) (5.29.3)
Requirement already satisfied: pydantic in d:\anaconda\lib\site-packages (from google-generativeai) (2.10.3)
Requirement already satisfied: tqdm in d:\anaconda\lib\site-packages (from google-generativeai) (4.67.1)
Requirement already satisfied: typing-extensions in d:\anaconda\lib\site-packages (from google-generativeai) (4.15.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in d:\anaconda\lib\site-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.27.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in d:\anaconda\lib\site-packages (from google-api-core->google-generativeai) (1.72.0)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in d:\anaconda\lib\site-packages (from google-api-core->google-generativeai) (2.32.3)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in d:\anaconda\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.76.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in d:\anaconda\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in d:\anaconda\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (0.2.8)
Requirement already satisfied: cryptography>=38.0.3 in d:\anaconda\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (44.0.1)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda\lib\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\lib\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda\lib\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\lib\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2025.4.26)
Requirement already satisfied: numpy>=1.26.0 in d:\anaconda\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\acer\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: cffi>=1.12 in d:\anaconda\lib\site-packages (from cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (1.17.1)
Requirement already satisfied: pycparser in d:\anaconda\lib\site-packages (from cffi>=1.12->cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (2.21)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in d:\anaconda\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.4.8)
Requirement already satisfied: six>=1.5 in d:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in d:\anaconda\lib\site-packages (from google-api-python-client->google-generativeai) (0.31.2)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in d:\anaconda\lib\site-packages (from google-api-python-client->google-generativeai) (0.3.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in d:\anaconda\lib\site-packages (from google-api-python-client->google-generativeai) (4.2.0)
Requirement already satisfied: pyparsing<4,>=3.1 in d:\anaconda\lib\site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in d:\anaconda\lib\site-packages (from pydantic->google-generativeai) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in d:\anaconda\lib\site-packages (from pydantic->google-generativeai) (2.27.1)
Requirement already satisfied: colorama in c:\users\acer\appdata\roaming\python\python313\site-packages (from tqdm->google-generativeai) (0.4.6)
Using cached google_generativeai-0.8.6-py3-none-any.whl (155 kB)
Installing collected packages: google-generativeai
Successfully installed google-generativeai-0.8.6
Note: you may need to restart the kernel to use updated packages.

In [8]:
%pip uninstall google-generativeai -y
%pip install -U google-generativeai

Found existing installation: google-generativeai 0.8.6
Uninstalling google-generativeai-0.8.6:
  Successfully uninstalled google-generativeai-0.8.6
Note: you may need to restart the kernel to use updated packages.
Collecting google-generativeai
  Using cached google_generativeai-0.8.6-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in d:\anaconda\lib\site-packages (from google-generativeai) (0.6.15)
Requirement already satisfied: google-api-core in d:\anaconda\lib\site-packages (from google-generativeai) (2.29.0)
Requirement already satisfied: google-api-python-client in d:\anaconda\lib\site-packages (from google-generativeai) (2.188.0)
Requirement already satisfied: google-auth>=2.15.0 in d:\anaconda\lib\site-packages (from google-generativeai) (2.49.0.dev0)
Requirement already satisfied: protobuf in d:\anaconda\lib\site-packages (from google-generativeai) (5.29.3)
Requirement already satisfied: pydantic in d:\anaconda\lib\site-packages (from google-generativeai) (2.13.4)
Requirement already satisfied: tqdm in d:\anaconda\lib\site-packages (from google-generativeai) (4.67.1)
Requirement already satisfied: typing-extensions in d:\anaconda\lib\site-packages (from google-generativeai) (4.15.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in d:\anaconda\lib\site-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.27.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in d:\anaconda\lib\site-packages (from google-api-core->google-generativeai) (1.72.0)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in d:\anaconda\lib\site-packages (from google-api-core->google-generativeai) (2.32.3)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in d:\anaconda\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.76.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in d:\anaconda\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in d:\anaconda\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (0.2.8)
Requirement already satisfied: cryptography>=38.0.3 in d:\anaconda\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (44.0.1)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda\lib\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\lib\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda\lib\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\lib\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2025.4.26)
Requirement already satisfied: cffi>=1.12 in d:\anaconda\lib\site-packages (from cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (1.17.1)
Requirement already satisfied: pycparser in d:\anaconda\lib\site-packages (from cffi>=1.12->cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (2.21)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in d:\anaconda\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.4.8)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in d:\anaconda\lib\site-packages (from google-api-python-client->google-generativeai) (0.31.2)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in d:\anaconda\lib\site-packages (from google-api-python-client->google-generativeai) (0.3.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in d:\anaconda\lib\site-packages (from google-api-python-client->google-generativeai) (4.2.0)
Requirement already satisfied: pyparsing<4,>=3.1 in d:\anaconda\lib\site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in d:\anaconda\lib\site-packages (from pydantic->google-generativeai) (0.6.0)
Requirement already satisfied: pydantic-core==2.46.4 in d:\anaconda\lib\site-packages (from pydantic->google-generativeai) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in d:\anaconda\lib\site-packages (from pydantic->google-generativeai) (0.4.2)
Requirement already satisfied: colorama in c:\users\acer\appdata\roaming\python\python313\site-packages (from tqdm->google-generativeai) (0.4.6)
Using cached google_generativeai-0.8.6-py3-none-any.whl (155 kB)
Installing collected packages: google-generativeai
Successfully installed google-generativeai-0.8.6
Note: you may need to restart the kernel to use updated packages.

In [9]:
import google.generativeai as genai

genai.configure(api_key="AQ.Ab8RN6LQ4AuyQCJoyv20GYY91WqXjT0RW1fgleD06mFsPagKPw")

for model in genai.list_models():
    if "generateContent" in model.supported_generation_methods:
        print(model.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-4-26b-a4b-it
models/gemma-4-31b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-3-pro-preview
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3.1-flash-lite
models/gemini-3-pro-image-preview
models/gemini-3-pro-image
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/gemini-3.1-flash-image
models/gemini-3.5-flash
models/lyria-3-clip-preview
models/lyria-3-pro-preview
models/gemini-3.1-flash-tts-preview
models/gemini-robotics-er-1.5-preview
models/gemini-robotics-er-1.6-preview
models/gemini-2.5-computer-use-preview-10-2025
models/antigravity-preview-05-2026
models/deep-research-max-preview-04-2026
models/deep-research-preview-04-2026
models/deep-research-pro-preview-12-2025

In [11]:
import google.generativeai as genai

genai.configure(api_key="AQ.Ab8RN6LQ4AuyQCJoyv20GYY91WqXjT0RW1fgleD06mFsPagKPw")

model = genai.GenerativeModel("models/gemini-2.5-flash")

response = model.generate_content(
    "What is Artificial Intelligence?"
)

print(response.text)

**Artificial Intelligence (AI)** is a broad field of computer science dedicated to creating machines that can **perform tasks that typically require human intelligence**.

In simpler terms, it's about making computers "smart" enough to learn, reason, solve problems, perceive, and understand language, much like humans do.

Here's a breakdown of what that means:

1.  **Learning:** AI systems can acquire information and rules for using the information, often without being explicitly programmed for every scenario. This is the realm of **Machine Learning (ML)**, where algorithms learn from data to identify patterns and make predictions or decisions.
2.  **Reasoning:** They can use acquired information to draw conclusions, make inferences, and find the best solution to a given problem.
3.  **Problem-Solving:** AI can analyze a situation, understand the goals, and devise a plan to achieve them.
4.  **Perception:** AI systems can interpret sensory input, like images (Computer Vision) and sounds (Speech Recognition), to understand the world around them.
5.  **Language Understanding:** They can process and understand human language (Natural Language Processing - NLP) and even generate human-like text or speech.

---

### Key Concepts & Sub-fields of AI:

*   **Machine Learning (ML):** A subset of AI that focuses on enabling systems to learn from data without explicit programming. It's the engine behind many AI applications.
    *   **Deep Learning (DL):** A sub-field of ML that uses artificial neural networks with multiple layers (hence "deep") to learn complex patterns from large amounts of data. This powers much of today's advanced AI.
*   **Natural Language Processing (NLP):** Deals with the interaction between computers and human language, including understanding, interpreting, and generating human language.
*   **Computer Vision (CV):** Enables computers to "see" and interpret visual information from the world, like images and videos.
*   **Robotics:** Integrates AI with physical machines to create intelligent robots capable of performing tasks autonomously.
*   **Expert Systems:** Older AI systems designed to mimic the decision-making ability of a human expert within a narrow domain, often using rule-based logic.
*   **Generative AI:** A newer class of AI models that can create new content (text, images, audio, video) based on patterns learned from training data. Examples include ChatGPT and DALL-E.

---

### Types of AI:

AI is often categorized by its capabilities:

1.  **Narrow AI (or Weak AI):** This is all the AI that exists today. It's designed and trained for a **specific task**.
    *   *Examples:* Voice assistants (Siri, Alexa), recommendation engines (Netflix, Amazon), spam filters, self-driving cars (performing the task of driving).
2.  **General AI (AGI or Strong AI):** This is hypothetical AI that would possess human-level cognitive abilities across **all intellectual tasks**. It could learn any intellectual task that a human being can. We are not there yet.
3.  **Superintelligence (ASI):** A hypothetical AI that would surpass human intelligence across virtually every field, including scientific creativity, general wisdom, and social skills.

---

### Why is AI important?

AI is rapidly transforming industries and daily life by:
*   Automating repetitive tasks
*   Analyzing vast amounts of data to uncover insights
*   Improving efficiency and decision-making
*   Enabling new discoveries in science and medicine
*   Creating personalized experiences

In essence, AI aims to replicate and eventually augment human intelligence, leading to machines that can perceive, understand, act, and learn with increasing autonomy and effectiveness.

In [12]:
import google.generativeai as genai
import pandas as pd

genai.configure(api_key="AQ.Ab8RN6LQ4AuyQCJoyv20GYY91WqXjT0RW1fgleD06mFsPagKPw")

models = [
    "models/gemini-2.0-flash",
    "models/gemini-2.5-flash",
    "models/gemini-2.5-pro"
]

prompt = "Explain Artificial Intelligence in 100 words."

results = []

for model_name in models:
    try:
        model = genai.GenerativeModel(model_name)
        response = model.generate_content(prompt)

        results.append({
            "Model": model_name,
            "Response Length": len(response.text),
            "Response": response.text[:300]
        })

        print(f"✓ Completed: {model_name}")

    except Exception as e:
        print(f"✗ Error in {model_name}: {e}")

df = pd.DataFrame(results)

df

✗ Error in models/gemini-2.0-flash: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-2.0-flash
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-2.0-flash
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-2.0-flash
Please retry in 37.900132349s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
}
violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
}
violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_input_token_count"
  quota_id: "GenerateContentInputTokensPerModelPerMinute-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
}
, retry_delay {
  seconds: 37
}
]
✓ Completed: models/gemini-2.5-flash
✗ Error in models/gemini-2.5-pro: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-2.5-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-2.5-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-2.5-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-2.5-pro
Please retry in 32.755767467s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_input_token_count"
  quota_id: "GenerateContentInputTokensPerModelPerDay-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-pro"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
}
violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-pro"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
}
violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-pro"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
}
violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_input_token_count"
  quota_id: "GenerateContentInputTokensPerModelPerMinute-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-pro"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
}
, retry_delay {
  seconds: 32
}
]

,Model,Response Length,Response
0,models/gemini-2.5-flash,740,Artificial Intelligence (AI) develops computer...

In [13]:
df.to_csv("llm_comparison_results.csv", index=False)
print("Results saved successfully!")

Results saved successfully!

***Task 2 - Prompt Engineering Playground***

In [15]:
import google.generativeai as genai

API_KEY = "AQ.Ab8RN6LQ4AuyQCJoyv20GYY91WqXjT0RW1fgleD06mFsPagKPw"

genai.configure(api_key=API_KEY)

for model in genai.list_models():
    print(model.name)
    break

print("API Connected Successfully!")

models/gemini-2.5-flash
API Connected Successfully!

In [16]:
import google.generativeai as genai
import pandas as pd

genai.configure(api_key="AQ.Ab8RN6LQ4AuyQCJoyv20GYY91WqXjT0RW1fgleD06mFsPagKPw")

model = genai.GenerativeModel("models/gemini-2.5-flash")

prompts = {
    "Zero Shot": "Explain Machine Learning.",
    "Few Shot": """
Example:
AI = Artificial Intelligence
ML = Machine Learning
DL = Deep Learning

Explain Data Science in the same style.
""",
    "Chain of Thought": """
Explain step by step how a student can learn Data Science from scratch.
"""
}

results = []

for prompt_type, prompt in prompts.items():
    try:
        response = model.generate_content(prompt)

        results.append({
            "Prompt Type": prompt_type,
            "Response": response.text
        })

        print(f"✓ {prompt_type} completed")

    except Exception as e:
        print(f"✗ Error in {prompt_type}: {e}")

df = pd.DataFrame(results)
df

✓ Zero Shot completed
✓ Few Shot completed
✓ Chain of Thought completed

        Prompt Type                                           Response
0         Zero Shot  Machine Learning (ML) is a subset of Artificia...
1          Few Shot  DS = Data Science = The scientific field of ex...
2  Chain of Thought  Learning Data Science from scratch is an excit...

***Task 3: Streaming AI Chat Assistant***

In [17]:
import google.generativeai as genai
genai.configure(api_key="AQ.Ab8RN6LQ4AuyQCJoyv20GYY91WqXjT0RW1fgleD06mFsPagKPw")
model = genai.GenerativeModel("models/gemini-2.5-flash")

In [19]:
while True:
    user_input = input("You: ")

    if user_input.lower() in ["exit", "quit"]:
        print("Chat ended!")
        break

    response = model.generate_content(user_input)

    print("\nAI:")
    print(response.text)
    print("-" * 50)

You:  What is Machine Learning?

AI:
Machine Learning (ML) is a subfield of **Artificial Intelligence (AI)** that focuses on giving computers the ability to **learn from data** without being explicitly programmed for every single task.

Instead of a human programmer writing specific, step-by-step instructions for every possible scenario, an ML algorithm is *trained* on a large dataset. During this training, it identifies patterns, relationships, and structures within the data. Once trained, this "learned model" can then make predictions, classifications, or decisions on *new, unseen data*.

**Think of it like this:**

*   **Traditional Programming:** You write a recipe for a computer: "If ingredient A is present, and ingredient B is present, then bake a cake."
*   **Machine Learning:** You give the computer thousands of successful cake recipes (ingredients, oven temperature, baking time, photos of the results). The computer "learns" what makes a good cake, and when given a new set of ingredients, it can predict if they will make a good cake, or even suggest optimal baking parameters, without you ever explicitly telling it the exact rules.

**Key Concepts in Machine Learning:**

1.  **Data:** This is the fuel for ML. The quantity and quality of data directly impact how well a machine learning model can learn and perform. Data can be numbers, text, images, audio, etc.
2.  **Algorithms:** These are the mathematical "recipes" or methods that a machine uses to learn from data. Examples include decision trees, neural networks, support vector machines, clustering algorithms, etc.
3.  **Model:** This is the *output* of the learning process. It's the "brain" or the set of learned rules/patterns that the algorithm creates after being trained on data. This model is then used to make predictions or decisions.
4.  **Training:** The process of feeding data to an algorithm so that it can learn and build a model.
5.  **Prediction/Inference:** Once a model is trained, it can be used to analyze new data and make a prediction or decision (e.g., "Is this email spam?", "What's the best route?", "Is this a cat or a dog?").

**How Machine Learning "Learns":**

*   **Input Data:** The algorithm is fed a dataset.
*   **Pattern Recognition:** It analyzes this data to identify statistical patterns, correlations, and features that distinguish different categories or predict certain outcomes.
*   **Model Adjustment:** Based on the patterns found and often through trial and error (comparing its predictions to known outcomes and adjusting its internal parameters), the algorithm refines its internal "model."
*   **Generalization:** The goal is for the model to generalize well, meaning it can apply its learned knowledge to new, previously unseen data, rather than just memorizing the training data.

**Types of Machine Learning:**

1.  **Supervised Learning:** The most common type. The algorithm learns from "labeled" data, meaning each piece of input data has a corresponding correct output.
    *   **Classification:** Predicts a category (e.g., spam/not spam, disease/no disease).
    *   **Regression:** Predicts a continuous value (e.g., house prices, stock values, temperature).
    *   *Examples:* Spam detection, image recognition (identifying objects), predicting customer churn.

2.  **Unsupervised Learning:** The algorithm learns from "unlabeled" data, finding hidden patterns or structures without being told what the "correct" output should be.
    *   **Clustering:** Groups similar data points together (e.g., customer segmentation).
    *   **Dimensionality Reduction:** Simplifies data by reducing the number of features while retaining important information.
    *   *Examples:* Recommender systems (Netflix, Amazon), anomaly detection (fraud detection), organizing large datasets.

3.  **Reinforcement Learning:** An agent learns to make decisions by interacting with an environment, receiving rewards for desired actions and penalties for undesirable ones, much like how a human learns through trial and error.
    *   *Examples:* Game playing (AlphaGo), robotics, self-driving cars.

**Why is Machine Learning Important?**

ML allows us to solve complex problems that are difficult or impossible to tackle with traditional programming. It enables systems to adapt, personalize experiences, automate tasks, and extract valuable insights from vast amounts of data, driving innovation across almost every industry.

In essence, Machine Learning is about building systems that improve their performance over time by continuously learning from the data they process.
--------------------------------------------------

You:  can you give me the roadmap for AI enginear

AI:
Becoming an AI Engineer is an exciting journey that blends strong software engineering principles with machine learning expertise. An AI Engineer is often responsible for building, deploying, and maintaining AI models in production environments, bridging the gap between data science research and scalable, reliable applications.

Here's a comprehensive roadmap:

---

### The AI Engineer Roadmap

**Goal:** To build, deploy, and manage AI/ML systems in production.

---

### Phase 1: Foundational Skills (The Bedrock)

This phase ensures you have a robust understanding of programming and core mathematical concepts essential for AI.

1.  **Programming Proficiency (Python is King):**
    *   **Core Python:** Data structures (lists, dicts, sets), control flow, functions, OOP (Object-Oriented Programming).
    *   **Standard Libraries:** `os`, `sys`, `json`, `logging`.
    *   **Best Practices:** Clean code, PEP 8, debugging.
    *   **Version Control:** Git & GitHub (essential for collaboration and tracking changes).

2.  **Mathematics & Statistics:**
    *   **Linear Algebra:** Vectors, matrices, dot products, eigenvalues (understanding how data is represented and transformed).
    *   **Calculus:** Derivatives, gradients (for understanding optimization algorithms like gradient descent).
    *   **Probability & Statistics:** Probability distributions, hypothesis testing, confidence intervals, descriptive statistics (mean, median, mode), inferential statistics (foundational for understanding model behavior and evaluation).

3.  **Data Structures & Algorithms:**
    *   Understanding common data structures (arrays, linked lists, trees, hash tables) and algorithms (sorting, searching) helps in writing efficient code and understanding the complexity of ML algorithms.

4.  **Basic Software Engineering Principles:**
    *   **Databases:** SQL (for querying and managing data), basic understanding of NoSQL (e.g., MongoDB, Redis) concepts.
    *   **Operating Systems:** Linux command line basics, understanding processes, memory, file systems.
    *   **Networking Basics:** HTTP/HTTPS, APIs (how applications communicate).

---

### Phase 2: Core Machine Learning & Data Science

This phase dives into the fundamentals of machine learning, data handling, and common algorithms.

1.  **Data Manipulation & Analysis:**
    *   **NumPy:** Numerical computing, array operations.
    *   **Pandas:** Data loading, cleaning, manipulation, analysis (DataFrames).
    *   **Matplotlib/Seaborn:** Data visualization.

2.  **Machine Learning Fundamentals:**
    *   **Concepts:** Supervised vs. Unsupervised Learning, Regression vs. Classification, Bias-Variance Tradeoff, Overfitting/Underfitting.
    *   **Algorithms:**
        *   **Regression:** Linear Regression, Polynomial Regression.
        *   **Classification:** Logistic Regression, Decision Trees, Random Forests, Support Vector Machines (SVMs), k-Nearest Neighbors (k-NN).
        *   **Clustering:** k-Means, DBSCAN.
        *   **Ensemble Methods:** Bagging, Boosting (e.g., Gradient Boosting, XGBoost, LightGBM).
    *   **Scikit-learn:** Hands-on implementation of various ML algorithms and preprocessing techniques.

3.  **Model Evaluation & Selection:**
    *   **Metrics:** Accuracy, Precision, Recall, F1-score, ROC-AUC (for classification); MSE, RMSE, MAE (for regression).
    *   **Techniques:** Cross-validation, Grid Search, Random Search, Hyperparameter Tuning.

4.  **Feature Engineering:**
    *   Understanding how to create, transform, and select features to improve model performance.

---

### Phase 3: Deep Learning & Advanced ML Concepts

Delve into neural networks and more complex AI models.

1.  **Deep Learning Fundamentals:**
    *   **Neural Networks:** Perceptrons, Multi-Layer Perceptrons (MLPs), activation functions.
    *   **Architectures:**
        *   **Convolutional Neural Networks (CNNs):** For image processing (e.g., image classification, object detection).
        *   **Recurrent Neural Networks (RNNs), LSTMs, GRUs:** For sequential data (e.g., natural language processing, time series).
        *   **Transformers:** The state-of-the-art for many NLP and increasingly CV tasks.
    *   **Transfer Learning:** Using pre-trained models.

2.  **Deep Learning Frameworks:**
    *   **TensorFlow / Keras:** (Easier entry point with Keras API).
    *   **PyTorch:** (More Pythonic, often preferred in research, but also production-ready).
    *   *Choose one to specialize in, but be aware of the other.*

3.  **Specialized Domains (Choose 1-2 based on interest):**
    *   **Natural Language Processing (NLP):** Word embeddings (Word2Vec, GloVe), BERT, GPT-x, text classification, sentiment analysis, named entity recognition.
    *   **Computer Vision (CV):** Image classification, object detection (YOLO, Faster R-CNN), image segmentation.
    *   **Generative AI:** GANs, VAEs, Diffusion Models (basic understanding).

---

### Phase 4: MLOps & Production Engineering (The "Engineer" Part)

This is where the AI Engineer truly shines – taking models from experiments to robust, scalable production systems.

1.  **Containerization (Docker):**
    *   Build, run, and manage Docker containers for reproducible environments and model deployment.

2.  **Cloud Platforms (Choose 1 to specialize in):**
    *   **AWS:** EC2, S3, SageMaker, Lambda, SQS/SNS.
    *   **GCP:** Compute Engine, Cloud Storage, AI Platform (Vertex AI), Cloud Functions, Pub/Sub.
    *   **Azure:** Virtual Machines, Blob Storage, Azure Machine Learning, Azure Functions.
    *   *Understand fundamental services: compute, storage, serverless, messaging, and managed ML services.*

3.  **Model Deployment & Serving:**
    *   **API Frameworks:** FastAPI, Flask (for building REST APIs to serve models).
    *   **Model Serving:** TensorFlow Serving, TorchServe, BentoML, Triton Inference Server.
    *   **Batch vs. Real-time Inference:** Understanding the trade-offs and appropriate solutions.

4.  **ML Pipelines & Orchestration:**
    *   **Pipeline Tools:** Apache Airflow, Kubeflow Pipelines, Prefect, MLflow (for tracking experiments, managing models).
    *   **Data Orchestration:** ETL/ELT concepts, data warehousing (e.g., Snowflake, BigQuery).

5.  **Monitoring & Logging:**
    *   **Model Performance:** Drift detection (data drift, concept drift), anomaly detection.
    *   **System Performance:** Latency, throughput, error rates.
    *   **Tools:** Prometheus, Grafana, custom logging frameworks.

6.  **CI/CD for ML:**
    *   Automating testing, building, and deploying ML models and associated infrastructure.
    *   GitHub Actions, GitLab CI/CD, Jenkins.

7.  **Scalability & Reliability:**
    *   Designing systems that can handle increased load and are resilient to failures.
    *   Load balancing, auto-scaling.

8.  **Security & Governance:**
    *   Data privacy (GDPR, HIPAA), model interpretability (Explainable AI - XAI), ethical AI considerations.

---

### Phase 5: Continuous Learning & Specialization

The AI field evolves rapidly, so continuous learning is paramount.

1.  **Stay Updated:** Read research papers (arXiv), follow prominent AI blogs, attend webinars/conferences.
2.  **Advanced Topics:** Reinforcement Learning, Graph Neural Networks, Causal Inference, Federated Learning, Quantum ML (emerging).
3.  **System Design:** Practice designing end-to-end AI systems, considering all components from data ingestion to model serving and monitoring.

---

### Key Principles for Success Throughout the Roadmap:

*   **Hands-on Projects:** Build, build, build! Start with simple projects and gradually increase complexity. Showcase them on GitHub.
*   **Deepen Understanding:** Don't just use libraries; understand the underlying algorithms and math.
*   **Read Documentation:** Become proficient at navigating official documentation.
*   **Community Engagement:** Join online forums (Stack Overflow, Reddit communities), attend meetups, network with other professionals.
*   **Practice Problem Solving:** LeetCode/HackerRank for coding challenges, Kaggle for ML competitions.
*   **Develop Soft Skills:** Communication, problem-solving, collaboration, critical thinking, and business acumen are crucial for successful deployment of AI solutions.

This roadmap is extensive but covers the breadth of what an AI Engineer needs to know. You don't need to master everything at once, but progressively working through these phases will equip you with the necessary skills to excel in this role. Good luck!
--------------------------------------------------

You:  exit

Chat ended!

***Report***
Built an interactive chatbot using Gemini API.
User can ask multiple questions in a single session.
The assistant generates real-time responses.
Exit command terminates the conversation

***Task 4: Token Usage & Cost Tracker***

In [20]:
import google.generativeai as genai
import pandas as pd

genai.configure(api_key="AQ.Ab8RN6LQ4AuyQCJoyv20GYY91WqXjT0RW1fgleD06mFsPagKPw")

model = genai.GenerativeModel("models/gemini-2.5-flash")

prompt = "Explain Artificial Intelligence."

response = model.generate_content(prompt)

response_text = response.text

# Approximate token count
token_count = len(response_text.split())

# Approximate cost calculation
cost_per_1000_tokens = 0.0001

estimated_cost = (token_count / 1000) * cost_per_1000_tokens

results = pd.DataFrame({
    "Prompt": [prompt],
    "Tokens Used": [token_count],
    "Estimated Cost ($)": [estimated_cost]
})

print(results)

                             Prompt  Tokens Used  Estimated Cost ($)
0  Explain Artificial Intelligence.          852            0.000085

In [21]:
results.to_csv("token_usage_report.csv", index=False)
print("Token usage report saved!")

Token usage report saved!

***Report Points for Task 4***
Tracked approximate token usage.
Estimated API cost based on token count.
Stored results in a structured DataFrame.
Exported token statistics to CSV for analysis.